version: "3.8"

services:

  redis:
    container_name: rediscache
    image: redis:alpine
    command:
      redis-server /usr/local/etc/redis.conf --requirepass qwerty
    volumes:
      - ./redis.conf:/usr/local/etc/redis.conf
    ports:
      - "6379:6379"

  postgres:
    container_name: postgres
    image: postgres
    volumes:
      - pg-data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"
    restart: unless-stopped

  app:
    container_name: app
    build: .
    volumes:
      - ./logs:/logs
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  pg-data:
  redis-data: