app:
  name: 'user-balance-api'
  version: '1.0.0'

http:
    port: 8080

logger:
  log_level: 'info'

postgres:
  pool_max: 20

converter:
  url: 'https://api.apilayer.com/exchangerates_data/convert'

redis:
  addr: 'rediscache:6379'
  db: 0
